# Numpy assignment
- Different tasks will be detailed by comments or text.
- For further reference and resources, it's advised to check out the NumPy documentation.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [3]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1,2,3,4,5])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3],[3,4,5]])

In [4]:
# Attributes of 1-dimensional array (shape, number of dimensions, data type, size and type)
print("Shape: ",arr1.shape)
print("number of dimensions: ",arr1.ndim)
print("data type: ",arr1.dtype)
print(" size: ",arr1. size)

Shape:  (5,)
number of dimensions:  1
data type:  int64
 size:  5


In [5]:
# Attributes of 2-dimensional array
print("Shape: ",arr2.shape)
print("number of dimensions: ",arr2.ndim)
print("data type: ",arr2.dtype)
print(" size: ",arr2. size)

Shape:  (2, 3)
number of dimensions:  2
data type:  int64
 size:  6


In [10]:
# Create an array of shape (5, 5) with only ones
arr5 = np.ones((5,5), np.int64)
arr5

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [13]:
# Create an array of shape (3, 3, 5) with only zeros
arr6 = np.zeros((3,3,5), np.int64)
arr6

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr7 = np.random.randint(0,10,(7,2), np.int64)
arr7

array([[4, 7],
       [7, 4],
       [4, 5],
       [9, 1],
       [9, 9],
       [8, 1],
       [5, 6]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr8 =np.random.rand(3,5)
arr8


array([[0.73561356, 0.45556709, 0.03952659, 0.41214395, 0.56321247],
       [0.48976663, 0.52486393, 0.50293486, 0.3430665 , 0.96118088],
       [0.49941558, 0.9272805 , 0.67948533, 0.38857813, 0.55050014]])

In [16]:
# Create an array of normally distributed random numbers
arr9 = np.random.randn(4)
arr9

array([-0.26339583,  0.62159379,  1.24530361, -0.33729123])

In [22]:
# Set the random seed to 42
np.random.seed(42)


# Create a random array of numbers between 0 & 10 of size (4, 6)
arr10 = np.random.randint(0,10,(4,6))
arr10

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [23]:
# Copy the code from the cell above and run it again
np.random.seed(42)
arr10 = np.random.randint(0,10,(4,6))
arr10

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [24]:
# Find the 0'th index of the latest array you created
print(arr10[0][0])


6


In [25]:
# Get the first 2 rows of latest array you created
r1=arr10[0]
r2=arr10[1]
print(r1, '\n', r2)

[6 3 7 4 6 9] 
 [2 6 7 4 3 7]


In [28]:
# Get the first 2 values of the first 2 rows of the latest array
r1v1 = r1[0]
r1v2= r2[0]
r2v1 = r2[0]
r2v2 = r2[1]
print( r1v1, r1v2,'\n', r2v1, r2v2)

6 2 
 2 6


In [32]:
# Create a random array of numbers between 0 & 10 and an array of ones both of size (3, 5), save them both to variables
ar1 = np.random.randint(0,10,(3,5))
ar2 = np.zeros((3,5), np.int64)


In [33]:
# Add the two arrays together
sum = ar1 + ar2

In [36]:
# Create another array of ones of shape (5, 3)
ar3 = np.ones((5,3), np.int64)

In [37]:
# Try add the array of ones and the other most recent array together # You can anticipate an error
sum1 = sum + ar3

ValueError: ignored

In [40]:
# Do the same operation you just did but this time with a transpose on one array
sum1 = sum + ar3.T
sum1

array([[ 9,  8,  5,  2,  5],
       [ 8, 10,  9,  9,  1],
       [ 9,  7,  9,  8,  1]])

In [41]:
# Take the latest array to the power of 2 using the python way
sum1**2

array([[ 81,  64,  25,   4,  25],
       [ 64, 100,  81,  81,   1],
       [ 81,  49,  81,  64,   1]])

In [42]:
# Do the same thing with numpy way
np.power(sum1,2)

array([[ 81,  64,  25,   4,  25],
       [ 64, 100,  81,  81,   1],
       [ 81,  49,  81,  64,   1]])

In [45]:
# Find the mean, min, max, standard deviation, variance of the latest array using np.mean()
print(np.mean(sum1),'\n',np.max(sum1),'\n',np.min(sum1),'\n',np.std(sum1),'\n',np.var(sum1))

6.666666666666667 
 10 
 1 
 3.0037014202850156 
 9.02222222222222


In [46]:
# Create two arrays of random integers between 0 to 10 one of size (3, 3) the other of size (3, 2)
z1=np.random.randint(0,10,(3,3))
z2=np.random.randint(0,10,(3,2))

In [48]:
# Perform a dot product on the two newest arrays you created
z3=np.dot(z1,z2)
z3

array([[138, 114],
       [ 75,  72],
       [ 42,  44]])

In [49]:
# Create two arrays of random integers between 0 to 10 both of size (4, 3)
y1 = np.random.randint(0,10,(4,3))
y2 = np.random.randint(0,10,(4,3))

In [51]:
# Perform a hadamard product on the two newest arrays you created
y3 = np.multiply(y1,y2)
y3

array([[14,  4,  0],
       [ 0, 24, 63],
       [24, 12, 56],
       [45, 18,  0]])

In [52]:
# Perform a dot product on the two newest arrays you created # Error anticipated
y4=np.dot(y1,y2)

ValueError: ignored

In [57]:
# Take the latest two arrays, perform a transpose on one of them and then perform a dot product on them both

y4=np.dot(y1,y2.T)
y4


array([[ 18,   4,  48,  72],
       [ 50,  87, 128, 122],
       [ 30,  71,  92,  68],
       [ 18,   8,  42,  63]])

In [58]:
# Create two arrays of random integers between 0 & 10 of the same shape and save them to variables
x1 = np.random.randint(0,10,(3,3))
x2 = np.random.randint(0,10,(3,3))

In [59]:
# Compare the two arrays with '>', '<=' and '==' 
x1>x2
x1<=x2
x1==x2


array([[False, False, False],
       [False, False, False],
       [False,  True, False]])

In [60]:
# Sort one of the arrays you just created in ascending order
np.sort(x1)

array([[0, 3, 6],
       [3, 4, 6],
       [3, 6, 6]])

In [61]:
# Sort the indexes of one of the arrays you just created
np.argsort(x1)

array([[1, 2, 0],
       [0, 1, 2],
       [1, 0, 2]])

In [62]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(x1)

0

In [65]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [66]:
# Find the indexes with the maximum values down the verticial axis of one of the arrays you created
np.argmax(x1,axis=1)

array([0, 2, 0])

In [67]:
# Find the indexes with the minimum values across the horizontal axis of one of the arrays you created
np.argmin(x1,axis=0)

array([1, 0, 0])